-- ============================================================
-- FarmTech Solutions - Fase 7
-- DDL equivalente ao schema SQLite, em sintaxe Oracle.
-- Recuperacao da entrega da Fase 3: estas tabelas podem ser
-- criadas no Oracle FIAP (oracle.fiap.com.br:1521/ORCL) e
-- populadas com os CSVs gerados por export_oracle.py, seguindo
-- o passo a passo de importacao do Oracle SQL Developer.
-- MER/DER documentado em docs/mer_der/modelo_dados.md
-- ============================================================

CREATE TABLE sensores (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR2(100) NOT NULL,
    tipo            VARCHAR2(50)  NOT NULL,
    localizacao     VARCHAR2(100),
    ativo           NUMBER(1) DEFAULT 1,
    data_instalacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE leituras_sensores (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id             NUMBER NOT NULL,
    timestamp             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    umidade_solo          NUMBER(6,2),
    temperatura_solo      NUMBER(6,2),
    ph_solo               NUMBER(4,2),
    temperatura_ar        NUMBER(6,2),
    umidade_ar            NUMBER(6,2),
    luminosidade          NUMBER(8,2),
    rendimento_kg_hectare NUMBER(8,2),
    CONSTRAINT fk_leitura_sensor FOREIGN KEY (sensor_id) REFERENCES sensores (id)
);

CREATE TABLE culturas (
    id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                   VARCHAR2(100) NOT NULL,
    tipo                   VARCHAR2(50)  NOT NULL,
    data_plantio           DATE,
    data_colheita_prevista DATE,
    area_hectares          NUMBER(10,4),
    sensor_id              NUMBER,
    CONSTRAINT fk_cultura_sensor FOREIGN KEY (sensor_id) REFERENCES sensores (id)
);

CREATE TABLE acoes_manejo (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cultura_id NUMBER NOT NULL,
    tipo_acao  VARCHAR2(50) NOT NULL,
    descricao  VARCHAR2(1000),
    quantidade NUMBER(10,2),
    unidade    VARCHAR2(20),
    data_acao  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    executada  NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_acao_cultura FOREIGN KEY (cultura_id) REFERENCES culturas (id)
);

CREATE TABLE producao (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cultura_id            NUMBER NOT NULL,
    data_colheita         DATE,
    rendimento_kg_hectare NUMBER(8,2),
    qualidade             VARCHAR2(50),
    observacoes           VARCHAR2(1000),
    CONSTRAINT fk_producao_cultura FOREIGN KEY (cultura_id) REFERENCES culturas (id)
);

CREATE TABLE previsoes (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id           NUMBER NOT NULL,
    timestamp           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    umidade_prevista    NUMBER(6,2),
    ph_previsto         NUMBER(4,2),
    rendimento_previsto NUMBER(8,2),
    confianca           NUMBER(5,4),
    CONSTRAINT fk_previsao_sensor FOREIGN KEY (sensor_id) REFERENCES sensores (id)
);

CREATE TABLE eventos_irrigacao (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    umidade        NUMBER(6,2),
    ph_ldr         NUMBER(6),
    nivel_n        NUMBER(1),
    nivel_p        NUMBER(1),
    nivel_k        NUMBER(1),
    previsao_chuva NUMBER(1),
    bomba_ligada   NUMBER(1),
    motivo         VARCHAR2(500),
    fonte          VARCHAR2(50) DEFAULT 'simulador'
);

CREATE TABLE deteccoes_visao (
    id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    imagem    VARCHAR2(255) NOT NULL,
    classe    VARCHAR2(50)  NOT NULL,
    confianca NUMBER(5,4),
    modelo    VARCHAR2(100)
);

CREATE TABLE alertas (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    origem         VARCHAR2(50) NOT NULL,
    tipo           VARCHAR2(50) NOT NULL,
    severidade     VARCHAR2(20) NOT NULL,
    mensagem       VARCHAR2(1000) NOT NULL,
    acao_corretiva VARCHAR2(1000),
    enviado_sns    NUMBER(1) DEFAULT 0,
    sns_message_id VARCHAR2(100)
);

-- Consultas de validacao (equivalentes aos prints pedidos na Fase 3):
-- SELECT * FROM leituras_sensores FETCH FIRST 20 ROWS ONLY;
-- SELECT sensor_id, AVG(umidade_solo), AVG(ph_solo) FROM leituras_sensores GROUP BY sensor_id;
-- SELECT origem, COUNT(*) FROM alertas GROUP BY origem;
